import React from 'react'

const About = () => {
  return (
    <div>
        <h1>About page</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat, distinctio aliquam perspiciatis delectus cupiditate libero id quasi laborum quia esse fugiat non, omnis iure corporis dolorem eligendi, impedit dolor nemo! Vitae iusto fuga, hic repellendus totam atque delectus suscipit quia facilis eius in. Autem suscipit neque architecto dolorem quo excepturi minima ipsum at esse quod perspiciatis omnis, cum placeat, a in unde dolore aperiam. Fugiat culpa beatae dolorum perspiciatis minus nihil autem neque iste doloremque quae alias ea pla animi perspiciatis quam. Qui delectus ut nam necessitatibus, error doloremque incidunt officia facere et maxime facilis quam tenetur aperiam deleniti. Minima aut, minus ipsam quae iure consequatur esse? Blanditiis rerum culpa tempore nam neque, totam corrupti a, alias, aliquam velit fugiat sequi? Ducimus libero nisi suscipit facere beatae facilis repudiandae at dolor voluptas in veritatis recusandae mollitia veniam fugit amet nihil sequi repellat doloremque, placeat voluptates accusamus aliquid! Tempora dolorem reiciendis debitis quia ea obcaecati nemo porro natus soluta a error, id eum voluptates? Mollitia, incidunt ut magnam expedita vero provident nemo explicabo rem temporibus a iusto tempore accusamus, unde exercitationem itaque corrupti doloribus consectetur earum molestias? Inventore quidem officia aliquid, ab autem quasi voluptatum dolorum doloremque esse enim neque modi animi illum, magni a qui voluptatem quam adipisci? Amet quia repudiandae voluptates vero, porro ducimus aut sit nam quasi adipisci dignissimos laborum ut impedit aliquid quae perferendis architecto? Eligendi totam, aut debitis sequi, asperiores maiores et at laboriosam, quia libero saepe quidem atque vel iusto similique! Reiciendis et saepe eos aliquam modi corporis. Consequatur, eum in eaque labore debitis earum ullam perferendis amet voluptatem repellendus asperiores. Ex, ad. Earum error eum esse omnis quaerat maiores ipsa non magnam ex dolore eaque sapiente autem accusamus dolor aliquid sequi, architecto tempora inventore quod a sit voluptatibus sunt. Tempora officiis eos veniam fugiat quasi aliquid! Quidem rerum quisquam perspiciatis ipsa praesentium repellat minus similique debitis, deleniti incidunt, magni velit provident recusandae, corporis necessitatibus quae dignissimos laboriosam aut quibusdam accusantium nostrum cumque expedita saepe. Cupiditate assumenda perspiciatis nemo expedita dignissimos? Quos beatae magnam suscipit odio molestias neque quas! Doloribus velit porro tempora consequatur distinctio dolorem amet aliquid ipsa earum repudiandae iste ab facere tenetur repellat laboriosam quos molestiae, aut excepturi numquam maxime est iusto? Adipisci, dolores labore, sint mollitia, voluptates eius distinctio maiores ipsum laborum voluptas hic tempore nulla accusamus. Distinctio odit dicta nulla hic beatae, perspiciatis ipsam in deleniti molestias tenetur vel.</p>
    </div>
  )
}

export default About;